/** Generated by scripts/generate-venue-heading-art.mjs. */
export const VENUE_HEADING_ART = {
  "sea-to-sky-gondola": {"src":"/images/venue-heading/sea-to-sky-gondola.svg","width":53.15,"height":26.7},
  "cheekye-ranch": {"src":"/images/venue-heading/cheekye-ranch.svg","width":78.5,"height":17.85},
  "sitka-farms": {"src":"/images/venue-heading/sitka-farms.svg","width":63.9,"height":17.85},
  "sunwolf": {"src":"/images/venue-heading/sunwolf.svg","width":52.85,"height":35.55},
  "squamish-valley-golf-club": {"src":"/images/venue-heading/squamish-valley-golf-club.svg","width":86.35,"height":26.7},
  "cheakamus-centre": {"src":"/images/venue-heading/cheakamus-centre.svg","width":57.4,"height":26.7},
  "glacier-valley-farm": {"src":"/images/venue-heading/glacier-valley-farm.svg","width":78.2,"height":26.7},
  "howe-sound-brewing": {"src":"/images/venue-heading/howe-sound-brewing.svg","width":60.1,"height":26.7},
  "house-of-lager-brewing-company": {"src":"/images/venue-heading/house-of-lager-brewing-company.svg","width":77.65,"height":35.55},
  "evans-lake": {"src":"/images/venue-heading/evans-lake.svg","width":59.35,"height":17.85},
  "brackendale-art-gallery": {"src":"/images/venue-heading/brackendale-art-gallery.svg","width":87.85,"height":26.7},
  "railway-museum-of-british-columbia": {"src":"/images/venue-heading/railway-museum-of-british-columbia.svg","width":82.8,"height":35.55},
  "capilano-university-squamish-campus": {"src":"/images/venue-heading/capilano-university-squamish-campus.svg","width":59.8,"height":44.4},
} as const;
